const ADD_PRODUCT = "ADD_PRODUCT";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const CLEAR_CART = "CLEAR_CART";
const SET_PRODUCTS = "SET_PRODUCTS";
const ROUTE_GROCERY = "ROUTE_GROCERY";
const ROUTE_CHECKOUT = "ROUTE_CHECKOUT";
const UPDATE_FORM = "UPDATE_FORM";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const UPDATE_ROUTE = "UPDATE_ROUTE";

export {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  UPDATE_PRODUCT,
  CLEAR_CART,
  SET_PRODUCTS,
  ROUTE_GROCERY,
  ROUTE_CHECKOUT,
    UPDATE_FORM,
    DELETE_PRODUCT,
    UPDATE_ROUTE
};