const ADD_PRODUCT = "ADD_PRODUCT";
const ROUTE_GROCERY = "ROUTE_GROCERY";
const ROUTE_CHECKOUT = "ROUTE_CHECKOUT";
const UPDATE_ROUTE = "UPDATE_ROUTE";
const ADD_TO_CART = "ADD_TO_CART";

export {
    ADD_PRODUCT,
    ROUTE_GROCERY,
    ROUTE_CHECKOUT,
    UPDATE_ROUTE,
    ADD_TO_CART
};